package crypto

import (
	goecdh "crypto/ecdh"
	"crypto/ecdsa"
	"crypto/x509"
	"encoding/pem"
	"fmt"
)

// parseECDHPublicKeyPEM parses a PEM-encoded PKIX public key and converts
// it to an *goecdh.PublicKey.  Accepts keys generated by gocryptic keygen
// --type ecdsa or --type ecdh (they use the same format).
func parseECDHPublicKeyPEM(data []byte) (*goecdh.PublicKey, error) {
	block, _ := pem.Decode(data)
	if block == nil {
		return nil, fmt.Errorf("no PEM block found")
	}
	pub, err := x509.ParsePKIXPublicKey(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("parsing PKIX public key: %w", err)
	}
	ecdsaPub, ok := pub.(*ecdsa.PublicKey)
	if !ok {
		return nil, fmt.Errorf("key is not an EC public key")
	}
	ecdhPub, err := ecdsaPub.ECDH()
	if err != nil {
		return nil, fmt.Errorf("converting to ECDH public key: %w", err)
	}
	return ecdhPub, nil
}

// parseECDHPrivateKeyPEM parses a PEM-encoded PKCS8 private key and converts
// it to an *goecdh.PrivateKey.
func parseECDHPrivateKeyPEM(data []byte) (*goecdh.PrivateKey, error) {
	block, _ := pem.Decode(data)
	if block == nil {
		return nil, fmt.Errorf("no PEM block found")
	}
	key, err := x509.ParsePKCS8PrivateKey(block.Bytes)
	if err != nil {
		// Try SEC1 EC key format as fallback.
		ecKey, err2 := x509.ParseECPrivateKey(block.Bytes)
		if err2 != nil {
			return nil, fmt.Errorf("parsing private key (tried PKCS8: %v, SEC1: %v)", err, err2)
		}
		return ecKey.ECDH()
	}
	ecdsaPriv, ok := key.(*ecdsa.PrivateKey)
	if !ok {
		return nil, fmt.Errorf("key is not an EC private key")
	}
	return ecdsaPriv.ECDH()
}