package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

var manCmd = &cobra.Command{
	Use:    "man",
	Short:  "Generate man pages for all GoCryptic commands",
	Hidden: true, // power-user command, not shown in --help
	Long: `Generate Unix man pages for gocryptic and all subcommands.

The pages are written to the output directory (default: ./man) and can
be installed system-wide with:

  sudo cp man/* /usr/local/share/man/man1/
  sudo mandb

Or for the current user only:

  mkdir -p ~/.local/share/man/man1
  cp man/* ~/.local/share/man/man1/
  mandb ~/.local/share/man/man1

EXAMPLES:
  gocryptic man                   # writes to ./man/
  gocryptic man --output /tmp/man # writes to /tmp/man/`,
	RunE: runMan,
}

var manOutput string

func init() {
	manCmd.Flags().StringVarP(&manOutput, "output", "o", "man",
		"Directory to write man pages into")
	rootCmd.AddCommand(manCmd)
}

func runMan(_ *cobra.Command, _ []string) error {
	if err := os.MkdirAll(manOutput, 0755); err != nil {
		return fmt.Errorf("creating output directory %s: %w", manOutput, err)
	}

	// cobra/doc uses the command's DisableAutoGenTag to suppress the
	// "Auto generated by spf13/cobra" footer.
	rootCmd.DisableAutoGenTag = true
	for _, sub := range rootCmd.Commands() {
		sub.DisableAutoGenTag = true
	}

	header := &doc.GenManHeader{
		Title:   "GOCRYPTIC",
		Section: "1",
		Date:    func() *time.Time { t := time.Now(); return &t }(),
		Source:  fmt.Sprintf("GoCryptic %s", version),
		Manual:  "GoCryptic Manual",
	}

	if err := doc.GenManTree(rootCmd, header, manOutput); err != nil {
		return fmt.Errorf("generating man pages: %w", err)
	}

	// List what was generated.
	entries, err := os.ReadDir(manOutput)
	if err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "Generated %d man page(s) in %s/\n\n", len(entries), manOutput)
	for _, e := range entries {
		success("%s", filepath.Join(manOutput, e.Name()))
	}

	fmt.Fprintf(os.Stderr, `
Install system-wide:
  sudo cp %s/* /usr/local/share/man/man1/ && sudo mandb

Install for current user:
  mkdir -p ~/.local/share/man/man1
  cp %s/* ~/.local/share/man/man1/ && mandb ~/.local/share/man/man1
`, manOutput, manOutput)

	return nil
}