// Package sign provides digital signature creation and verification.
// Both RSA-PSS (SHA-256) and ECDSA P-256 (ASN.1/DER) are supported;
// the key type is auto-detected from the PEM file.
package sign

import (
	"crypto"
	"crypto/ecdsa"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"os"
)

// Sign computes a digital signature over data using the private key at privKeyPath.
//
//   - RSA keys use RSA-PSS with SHA-256.
//   - ECDSA keys use ECDSA with SHA-256, signature encoded as ASN.1 DER.
//
// The key type is detected automatically from the PEM file (PKCS8, EC, or PKCS1).
func Sign(data []byte, privKeyPath string) ([]byte, error) {
	priv, err := loadPrivateKey(privKeyPath)
	if err != nil {
		return nil, err
	}
	digest := sha256.Sum256(data)
	switch k := priv.(type) {
	case *rsa.PrivateKey:
		sig, err := rsa.SignPSS(rand.Reader, k, crypto.SHA256, digest[:], nil)
		if err != nil {
			return nil, fmt.Errorf("RSA-PSS signing: %w", err)
		}
		return sig, nil
	case *ecdsa.PrivateKey:
		sig, err := ecdsa.SignASN1(rand.Reader, k, digest[:])
		if err != nil {
			return nil, fmt.Errorf("ECDSA signing: %w", err)
		}
		return sig, nil
	default:
		return nil, fmt.Errorf("unsupported private key type %T", priv)
	}
}

// Verify checks that sig is a valid signature of data under the public key
// at pubKeyPath.  Returns nil on success, a descriptive error otherwise.
func Verify(data, sig []byte, pubKeyPath string) error {
	pub, err := loadPublicKey(pubKeyPath)
	if err != nil {
		return err
	}
	digest := sha256.Sum256(data)
	switch k := pub.(type) {
	case *rsa.PublicKey:
		if err := rsa.VerifyPSS(k, crypto.SHA256, digest[:], sig, nil); err != nil {
			return fmt.Errorf("RSA-PSS verification failed: %w", err)
		}
		return nil
	case *ecdsa.PublicKey:
		if !ecdsa.VerifyASN1(k, digest[:], sig) {
			return fmt.Errorf("ECDSA signature is invalid")
		}
		return nil
	default:
		return fmt.Errorf("unsupported public key type %T", pub)
	}
}

// KeyType returns a human-readable description of the key algorithm found in a PEM file.
func KeyType(keyPath string) (string, error) {
	data, err := os.ReadFile(keyPath)
	if err != nil {
		return "", fmt.Errorf("reading %s: %w", keyPath, err)
	}
	block, _ := pem.Decode(data)
	if block == nil {
		return "", fmt.Errorf("no PEM block in %s", keyPath)
	}
	// Try each parser and return what matches.
	if k, err := x509.ParsePKCS8PrivateKey(block.Bytes); err == nil {
		switch k.(type) {
		case *rsa.PrivateKey:
			return "RSA private key (PKCS8)", nil
		case *ecdsa.PrivateKey:
			return "ECDSA private key (PKCS8)", nil
		}
	}
	if _, err := x509.ParseECPrivateKey(block.Bytes); err == nil {
		return "ECDSA private key (SEC1)", nil
	}
	if _, err := x509.ParsePKCS1PrivateKey(block.Bytes); err == nil {
		return "RSA private key (PKCS1)", nil
	}
	if k, err := x509.ParsePKIXPublicKey(block.Bytes); err == nil {
		switch k.(type) {
		case *rsa.PublicKey:
			return "RSA public key (PKIX)", nil
		case *ecdsa.PublicKey:
			return "ECDSA public key (PKIX)", nil
		}
	}
	return "unknown key type", nil
}

// ---------------------------------------------------------------------------
// Internal PEM loaders
// ---------------------------------------------------------------------------

func loadPrivateKey(path string) (crypto.PrivateKey, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading private key %s: %w", path, err)
	}
	block, _ := pem.Decode(data)
	if block == nil {
		return nil, fmt.Errorf("no PEM block found in %s", path)
	}
	// PKCS8 covers both RSA and ECDSA keys generated by gocryptic keygen.
	if k, err := x509.ParsePKCS8PrivateKey(block.Bytes); err == nil {
		return k, nil
	}
	// Legacy EC key (SEC1 format).
	if k, err := x509.ParseECPrivateKey(block.Bytes); err == nil {
		return k, nil
	}
	// Legacy RSA key (PKCS1).
	if k, err := x509.ParsePKCS1PrivateKey(block.Bytes); err == nil {
		return k, nil
	}
	return nil, fmt.Errorf("unable to parse private key from %s (tried PKCS8, SEC1, PKCS1)", path)
}

func loadPublicKey(path string) (crypto.PublicKey, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading public key %s: %w", path, err)
	}
	block, _ := pem.Decode(data)
	if block == nil {
		return nil, fmt.Errorf("no PEM block found in %s", path)
	}
	pub, err := x509.ParsePKIXPublicKey(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("parsing public key from %s: %w", path, err)
	}
	return pub, nil
}
