# This workflow will build and test a Golang project
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step to check out the code from the repository
      - uses: actions/checkout@v4

      # Step to set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x" # Use the latest stable Go 1.21.x version

      # Step to install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Step to build the project
      - name: Build the project
        run: go build -v ./...

      # Step to run tests
      - name: Run tests
        run: go test -v ./...
